name: Deploy to TestFlight

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.0'

jobs:
  deploy:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'
        bundler-cache: false
        
    - name: Install dependencies
      run: |
        flutter pub get
        cd ios
        # Install Ruby dependencies
        bundle install
        # Install CocoaPods dependencies
        bundle exec pod install
        
    - name: Build Flutter iOS
      run: |
        flutter clean
        flutter pub get
        flutter build ios --release --no-codesign
        
    - name: Setup Match
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      run: |
        cd ios
        bundle exec fastlane match_setup || echo "Match already configured"

    - name: Build and Deploy to TestFlight
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      run: |
        cd ios
        bundle exec fastlane beta
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Build and deployment to TestFlight completed successfully!"
        else
          echo "❌ Build and deployment to TestFlight failed!"
        fi
