name: Direct Deploy to TestFlight

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.0'

jobs:
  deploy:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.8'
        bundler-cache: true
        
    - name: Install dependencies
      run: |
        flutter pub get
        cd ios && bundle install
        
    - name: Build Flutter iOS
      run: |
        flutter clean
        flutter pub get
        flutter build ios --release --no-codesign
        
    - name: Build and Deploy to TestFlight
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      run: |
        cd ios
        # Increment build number
        bundle exec fastlane run increment_build_number xcodeproj:"Runner.xcodeproj"
        
        # Build the iOS app
        bundle exec fastlane run build_app \
          workspace:"Runner.xcworkspace" \
          scheme:"Runner" \
          export_method:"app-store" \
          export_options:"{method: 'app-store', teamID: '$TEAM_ID', uploadBitcode: false, uploadSymbols: true, compileBitcode: false}"
        
        # Upload to TestFlight
        bundle exec fastlane run upload_to_testflight \
          skip_waiting_for_build_processing:true \
          changelog:"New build with latest features and improvements"
        
    - name: Deployment Success
      if: success()
      run: |
        echo "🎉 App deployed to TestFlight successfully!"
        
    - name: Deployment Failed
      if: failure()
      run: |
        echo "❌ Deployment to TestFlight failed!"
        echo "Check the logs above for more details"
