name: Build and Deploy to TestFlight

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permite execução manual

env:
  FLUTTER_VERSION: '3.24.0'
  XCODE_VERSION: '15.4'

jobs:
  build-and-deploy:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.8'
        bundler-cache: true
        
    - name: Install Flutter dependencies
      run: flutter pub get
      
    - name: Run Flutter tests
      run: flutter test
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
        
    - name: Install iOS dependencies
      run: |
        cd ios
        bundle install
        
    - name: Build Flutter iOS
      run: |
        flutter clean
        flutter pub get
        flutter build ios --release --no-codesign
        
    - name: Build and Deploy to TestFlight
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      run: |
        cd ios
        bundle exec fastlane beta
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Build and deployment to TestFlight completed successfully!"
        else
          echo "❌ Build and deployment to TestFlight failed!"
        fi
